### ISSUE TITLE
Switch to Alpine linux from Debian

### ISSUE THREAD

**Issue by zrzka** [balena-io-examples/balena-rust-hello-world#9]
Just to make the images smaller and faster to download, build, ...

**Comment by zrzka** [comment]
It's not that easy as I thought.

* `rustup` doesn't work out of the box on Alpine, see [No init build against musl libc](https://github.com/rust-lang-nursery/rustup.rs/issues/354#issuecomment-368274346)
* There's ready to use [rust](https://pkgs.alpinelinux.org/packages?name=rust&branch=edge) package, but just for the `x86_64` architecture ([15 patches](https://github.com/alpinelinux/aports/tree/master/community/rust))

Will keep an eye on this and will wait till it will be properly supported.

**Comment by zrzka** [comment]
@raphaelcohn thanks for your Dockerfile. I'm thinking, thinking, not sure if this whole dance should be in this hello world example. I mean, hello world should very simple. Anyway, thanks again, I'll try it.

**Comment by raphaelcohn** [comment]
I'm currently re-writing some of this dockerfile to make it a bit more reproducible. My longer-term hope is to use mrustc to get a reproducible, versioned build.

**Comment by vipulgupta2048** [comment]
Superseded by #31
